env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
rules:
  no-eval: off
  no-mixed-operators: off
  "@typescript-eslint/strict-boolean-expressions": off
  "@typescript-eslint/restrict-plus-operands": off
  curly: off